name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
      - run: npm run typecheck --if-present
      - run: npm run build --if-present

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # Auth with your service-account JSON in repo secret GOOGLE_CLOUD_KEY
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_KEY }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_CLOUD_ID }}

      # Build & deploy straight from source (Cloud Build) to Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ secrets.CLOUD_RUN_SERVICE }}          # e.g. reivilo-b2b-api
          region:  ${{ secrets.GOOGLE_CLOUD_REGION }}        # e.g. africa-south1
          source: .
          flags: >-
            --allow-unauthenticated
            --memory=1Gi
            --cpu=1
            --port=8080
            --set-env-vars=NODE_ENV=production,PORT=8080,FROM_EMAIL=noreply@reiviloindustrial.co.za,SUPPORT_EMAIL=support@reiviloindustrial.co.za
            --set-secrets=DATABASE_URL=DATABASE_URL:latest,CIN7_ACCOUNT_ID=CIN7_ACCOUNT_ID:latest,CIN7_APP_KEY=CIN7_APP_KEY:latest,SENDGRID_API_KEY=SENDGRID_API_KEY:latest,SESSION_SECRET=SESSION_SECRET:latest,SYNC_TOKEN=SYNC_TOKEN:latest
